// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "./lib/language-context";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

// import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "@/components/ui/sonner";
import { getSEOMetadata } from "./lib/seo1";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = getSEOMetadata({
  title: "Wedison - Motor Listrik & SuperCharge Indonesia",
  description:
    "Wedison adalah produsen motor listrik dan teknologi supercharger terdepan di Indonesia. Temukan produk, spesifikasi, dan solusi kendaraan listrik modern di sini.",
  keywords: [
    "wedison",
    "motor listrik",
    "supercharge",
    "kendaraan listrik",
    "EV",
  ],
  url: "https://wedison.co",
  image: "https://wedison.co/wedison-sidebyside.png",
  lang: "id",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <Navbar />
          <div className="">{children}</div>
          {/* <div className=" pt-12 md:pt-16">{children}</div> */}
          {/* <SpeedInsights /> */}
          <Footer />
        </LanguageProvider>
        <Toaster
          toastOptions={{
            classNames: {
              description: "!text-gray-500",
            },
          }}
        />
      </body>
    </html>
  );
}
